### ISSUE TITLE
10/5/2020 weekly to-do list

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/codeNboba#101]
- [ ] Add an issue template to this repository for the weekly to-do issues

- [ ] To-do list for the mobile apps day

- [ ] To-do list for the machine learning days

- [ ] To-do list for the GitHub apps day

- [ ] Candidates for "What's new on GitHub"

**Comment by tianhaoz95** [comment]
**Mobile apps day**

- [ ] Getting started with the design for the to-do app for investors.
- [ ] Finish the docs for the overall design.
- [ ] Finish the repository structure.
- [ ] Finish the data structure definition.

**Comment by tianhaoz95** [comment]
What's new on GitHub candidates

- [rich](https://github.com/willmcgugan/rich): rich terminal output for Python

**Comment by tianhaoz95** [comment]
Looks like a polling service with great integration can be a good market.
